logging:
  level:
    org:
      springframework:
        web: INFO
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: 
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-ui
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true
    show-sql: true
    defer-datasource-initialization: true
    initialization-mode: always
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

